export const words = [
  { spanish: "de", english: "of, from", category: "preposition" },
  { spanish: "la", english: "the - feminine singular", category: "article" },
  { spanish: "que", english: "that, which", category: "conjunction" },
  { spanish: "el", english: "the - masculine singular", category: "article" },
  { spanish: "en", english: "in, on", category: "preposition" },
  { spanish: "y", english: "and", category: "conjunction" },
  { spanish: "a", english: "to, at", category: "preposition" },
  { spanish: "los", english: "the - masculine plural", category: "article" },
  { spanish: "se", english: "oneself, reflexive marker", category: "pronoun" },
  { spanish: "del", english: "of the, from the", category: "preposition" },
  { spanish: "las", english: "the - feminine plural", category: "article" },
  { spanish: "un", english: "a, an - masculine", category: "article" },
  { spanish: "por", english: "by, for", category: "preposition" },
  { spanish: "con", english: "with", category: "preposition" },
  { spanish: "no", english: "no", category: "adverb" },
  { spanish: "una", english: "a, an - feminine", category: "article" },
  { spanish: "su", english: "his, her, its, their", category: "pronoun" },
  { spanish: "para", english: "for, to", category: "preposition" },
  { spanish: "es", english: "is", category: "verb" },
  { spanish: "al", english: "to the", category: "preposition" },
  { spanish: "lo", english: "the - masculine singular", category: "pronoun" },
  { spanish: "como", english: "like, as", category: "conjunction" },
  { spanish: "más", english: "more", category: "adjective" },
  { spanish: "pero", english: "but", category: "conjunction" },
  {
    spanish: "sus",
    english: "his, her, its, their - plural",
    category: "pronoun",
  },
  {
    spanish: "le",
    english: "to him, to her, indirect object",
    category: "pronoun",
  },
  { spanish: "ha", english: "has", category: "verb" },
  { spanish: "me", english: "me", category: "pronoun" },
  { spanish: "si", english: "yes, if", category: "adverb" },
  { spanish: "sin", english: "without", category: "preposition" },
  { spanish: "sobre", english: "on, about", category: "preposition" },
  {
    spanish: "este",
    english: "this - masculine singular",
    category: "pronoun",
  },
  { spanish: "ya", english: "already, now", category: "adverb" },
  { spanish: "entre", english: "between, among", category: "preposition" },
  { spanish: "cuando", english: "when", category: "conjunction" },
  { spanish: "todo", english: "all, everything", category: "pronoun" },
  { spanish: "esta", english: "this - feminine singular", category: "pronoun" },
  { spanish: "ser", english: "to be", category: "verb" },
  { spanish: "son", english: "are", category: "verb" },
  { spanish: "también", english: "also", category: "adverb" },
  { spanish: "fue", english: "was, went", category: "verb" },
  { spanish: "había", english: "there was, there were", category: "verb" },
  { spanish: "era", english: "was", category: "verb" },
  { spanish: "muy", english: "very", category: "adverb" },
  { spanish: "años", english: "years", category: "noun" },
  { spanish: "hasta", english: "until, up to", category: "preposition" },
  { spanish: "desde", english: "from, since", category: "preposition" },
  { spanish: "está", english: "is - temporary state", category: "verb" },
  { spanish: "mi", english: "my", category: "pronoun" },
  { spanish: "porque", english: "because", category: "conjunction" },
  { spanish: "qué", english: "what", category: "pronoun" },
  { spanish: "él", english: "he", category: "pronoun" },
  { spanish: "esto", english: "this - neutral singular", category: "pronoun" },
  {
    spanish: "te",
    english: "you - direct/indirect object",
    category: "pronoun",
  },
  { spanish: "ella", english: "she", category: "pronoun" },
  { spanish: "nosotros", english: "we", category: "pronoun" },
  { spanish: "ustedes", english: "you - plural", category: "pronoun" },
  { spanish: "ellos", english: "they - masculine", category: "pronoun" },
  { spanish: "ellas", english: "they - feminine", category: "pronoun" },
  { spanish: "saber", english: "to know", category: "verb" },
  { spanish: "ver", english: "to see", category: "verb" },
  { spanish: "poder", english: "to be able to", category: "verb" },
  { spanish: "decir", english: "to say", category: "verb" },
  { spanish: "venir", english: "to come", category: "verb" },
  { spanish: "tomar", english: "to take, drink", category: "verb" },
  { spanish: "trabajar", english: "to work", category: "verb" },
  { spanish: "hacer", english: "to do, make", category: "verb" },
  { spanish: "pensar", english: "to think", category: "verb" },
  { spanish: "llegar", english: "to arrive", category: "verb" },
  { spanish: "hablar", english: "to speak", category: "verb" },
  { spanish: "ahora", english: "now", category: "adverb" },
  { spanish: "grande", english: "big, large", category: "adjective" },
  { spanish: "pequeño", english: "small", category: "adjective" },
  { spanish: "otra", english: "another", category: "pronoun" },
  { spanish: "mismo", english: "same", category: "adjective" },
  { spanish: "tiempo", english: "time", category: "noun" },
  { spanish: "lugar", english: "place", category: "noun" },
  { spanish: "vida", english: "life", category: "noun" },
  { spanish: "día", english: "day", category: "noun" },
  { spanish: "noche", english: "night", category: "noun" },
  { spanish: "semana", english: "week", category: "noun" },
  { spanish: "mes", english: "month", category: "noun" },
  { spanish: "año", english: "year", category: "noun" },
  { spanish: "gente", english: "people", category: "noun" },
  { spanish: "familia", english: "family", category: "noun" },
  { spanish: "amigo", english: "friend", category: "noun" },
  { spanish: "hombre", english: "man", category: "noun" },
  { spanish: "mujer", english: "woman", category: "noun" },
  { spanish: "niño", english: "child, boy", category: "noun" },
  { spanish: "niña", english: "girl", category: "noun" },
  { spanish: "trabajo", english: "work", category: "noun" },
  { spanish: "casa", english: "house", category: "noun" },
  { spanish: "ciudad", english: "city", category: "noun" },
  { spanish: "todos", english: "all, everyone", category: "pronoun" },
  { spanish: "nos", english: "us", category: "pronoun" },
  { spanish: "ese", english: "that - masculine singular", category: "pronoun" },
  { spanish: "alguien", english: "someone", category: "pronoun" },
  { spanish: "tener", english: "to have", category: "verb" },
  { spanish: "ir", english: "to go", category: "verb" },
  { spanish: "poner", english: "to put", category: "verb" },
  { spanish: "salir", english: "to leave, to go out", category: "verb" },
  { spanish: "parecer", english: "to seem", category: "verb" },
  { spanish: "creer", english: "to believe", category: "verb" },
  { spanish: "escribir", english: "to write", category: "verb" },
  { spanish: "llamar", english: "to call", category: "verb" },
  { spanish: "entrar", english: "to enter", category: "verb" },
  { spanish: "sentir", english: "to feel", category: "verb" },
  { spanish: "leer", english: "to read", category: "verb" },
  { spanish: "esperar", english: "to wait, to hope", category: "verb" },
  { spanish: "entender", english: "to understand", category: "verb" },
  { spanish: "momento", english: "moment", category: "noun" },
  { spanish: "hijo", english: "son", category: "noun" },
  { spanish: "hija", english: "daughter", category: "noun" },
  { spanish: "tiempo", english: "time, weather", category: "noun" },
  { spanish: "dinero", english: "money", category: "noun" },
  { spanish: "agua", english: "water", category: "noun" },
  { spanish: "comida", english: "food", category: "noun" },
  { spanish: "luz", english: "light", category: "noun" },
  { spanish: "camino", english: "path, road", category: "noun" },
  { spanish: "trabajo", english: "work, job", category: "noun" },
  { spanish: "cosa", english: "thing", category: "noun" },
  { spanish: "persona", english: "person", category: "noun" },
  { spanish: "tienda", english: "store", category: "noun" },
  { spanish: "libro", english: "book", category: "noun" },
  { spanish: "película", english: "movie", category: "noun" },
  { spanish: "coche", english: "car", category: "noun" },
  { spanish: "nuevo", english: "new", category: "adjective" },
  { spanish: "malo", english: "bad", category: "adjective" },
  { spanish: "interesante", english: "interesting", category: "adjective" },
  { spanish: "difícil", english: "difficult", category: "adjective" },
  { spanish: "mucho", english: "much", category: "adjective" },
  { spanish: "viejo", english: "old", category: "adjective" },
  { spanish: "además", english: "besides, furthermore", category: "adverb" },
  { spanish: "entonces", english: "then", category: "adverb" },
  { spanish: "luego", english: "later", category: "adverb" },
  { spanish: "lejos", english: "far", category: "adverb" },
  { spanish: "donde", english: "where", category: "adverb" },
  { spanish: "quiénes", english: "who (plural)", category: "pronoun" },
  { spanish: "algo", english: "something", category: "pronoun" },
  { spanish: "ninguno", english: "none", category: "pronoun" },
  { spanish: "algunos", english: "some (plural)", category: "pronoun" },
  { spanish: "ninguna", english: "none (feminine)", category: "pronoun" },
  { spanish: "nada", english: "nothing", category: "pronoun" },
  { spanish: "todo", english: "everything", category: "pronoun" },
  { spanish: "menos", english: "less", category: "adverb" },
  { spanish: "peor", english: "worse", category: "adjective" },
  { spanish: "pequeña", english: "small (feminine)", category: "adjective" },
  { spanish: "largo", english: "long", category: "adjective" },
  { spanish: "corto", english: "short", category: "adjective" },
  { spanish: "alto", english: "tall", category: "adjective" },
  { spanish: "bajo", english: "short, low", category: "adjective" },
  { spanish: "diferente", english: "different", category: "adjective" },
  { spanish: "igual", english: "equal, same", category: "adjective" },
  { spanish: "quizás", english: "perhaps", category: "adverb" },
  { spanish: "todavía", english: "still, yet", category: "adverb" },
  { spanish: "nuevamente", english: "again", category: "adverb" },
  { spanish: "de repente", english: "suddenly", category: "adverb" },
  { spanish: "inmediatamente", english: "immediately", category: "adverb" },
  { spanish: "casi", english: "almost", category: "adverb" },
  { spanish: "apenas", english: "barely", category: "adverb" },
  { spanish: "cierto", english: "certain", category: "adjective" },
  { spanish: "falso", english: "false", category: "adjective" },
  { spanish: "probable", english: "probable", category: "adjective" },
  { spanish: "improbable", english: "unlikely", category: "adjective" },
  { spanish: "verdadero", english: "true", category: "adjective" },
  { spanish: "cualquiera", english: "anyone", category: "pronoun" },
  { spanish: "bastante", english: "enough", category: "adverb" },
  { spanish: "algún", english: "some", category: "adjective" },
  { spanish: "deber", english: "should", category: "verb" },
  { spanish: "comer", english: "to eat", category: "verb" },
  { spanish: "beber", english: "to drink", category: "verb" },
  { spanish: "vivir", english: "to live", category: "verb" },
  { spanish: "escuchar", english: "to listen", category: "verb" },
  { spanish: "mirar", english: "to look", category: "verb" },
  { spanish: "quedar", english: "to stay", category: "verb" },
  { spanish: "volver", english: "to return", category: "verb" },
  { spanish: "tocar", english: "to touch, play", category: "verb" },
  { spanish: "acabar", english: "to finish", category: "verb" },
  { spanish: "comprar", english: "to buy", category: "verb" },
  { spanish: "bailar", english: "to dance", category: "verb" },
  { spanish: "contar", english: "to count, tell", category: "verb" },
  { spanish: "correr", english: "to run", category: "verb" },
  { spanish: "caminar", english: "to walk", category: "verb" },
  { spanish: "dar", english: "to give", category: "verb" },
  { spanish: "traer", english: "to bring", category: "verb" },
  { spanish: "dejar", english: "to leave", category: "verb" },
  { spanish: "decidir", english: "to decide", category: "verb" },
  { spanish: "querer", english: "to want", category: "verb" },
  { spanish: "rojo", english: "red", category: "adjective" },
  { spanish: "azul", english: "blue", category: "adjective" },
  { spanish: "verde", english: "green", category: "adjective" },
  { spanish: "amarillo", english: "yellow", category: "adjective" },
  { spanish: "negro", english: "black", category: "adjective" },
  { spanish: "blanco", english: "white", category: "adjective" },
  { spanish: "gris", english: "gray", category: "adjective" },
  { spanish: "marrón", english: "brown", category: "adjective" },
  { spanish: "naranja", english: "orange", category: "adjective" },
  { spanish: "morado", english: "purple", category: "adjective" },
  { spanish: "rosa", english: "pink", category: "adjective" },
  { spanish: "violeta", english: "violet", category: "adjective" },
  { spanish: "oro", english: "gold", category: "adjective" },
  { spanish: "plateado", english: "silver", category: "adjective" },
  { spanish: "lunes", english: "monday", category: "noun" },
  { spanish: "martes", english: "tuesday", category: "noun" },
  { spanish: "miércoles", english: "wednesday", category: "noun" },
  { spanish: "jueves", english: "thursday", category: "noun" },
  { spanish: "viernes", english: "friday", category: "noun" },
  { spanish: "sábado", english: "saturday", category: "noun" },
  { spanish: "domingo", english: "sunday", category: "noun" },
  { spanish: "enero", english: "january", category: "noun" },
  { spanish: "febrero", english: "february", category: "noun" },
  { spanish: "marzo", english: "march", category: "noun" },
  { spanish: "abril", english: "april", category: "noun" },
  { spanish: "mayo", english: "may", category: "noun" },
  { spanish: "junio", english: "june", category: "noun" },
  { spanish: "julio", english: "july", category: "noun" },
  { spanish: "agosto", english: "august", category: "noun" },
  { spanish: "septiembre", english: "september", category: "noun" },
  { spanish: "octubre", english: "october", category: "noun" },
  { spanish: "noviembre", english: "november", category: "noun" },
  { spanish: "diciembre", english: "december", category: "noun" },
  { spanish: "hoy", english: "today", category: "adverb" },
  { spanish: "mañana", english: "tomorrow", category: "adverb" },
  { spanish: "ayer", english: "yesterday", category: "adverb" },
  { spanish: "primavera", english: "spring", category: "noun" },
  { spanish: "verano", english: "summer", category: "noun" },
  { spanish: "otoño", english: "autumn", category: "noun" },
  { spanish: "invierno", english: "winter", category: "noun" },
  { spanish: "calendario", english: "calendar", category: "noun" },
  { spanish: "fecha", english: "date", category: "noun" },
  { spanish: "fin de semana", english: "weekend", category: "noun" },
  { spanish: "tarde", english: "afternoon", category: "noun" },
  { spanish: "mañana", english: "morning", category: "noun" },
  { spanish: "mediodía", english: "noon", category: "noun" },
  { spanish: "medianoche", english: "midnight", category: "noun" },
  { spanish: "hora", english: "hour", category: "noun" },
  { spanish: "minuto", english: "minute", category: "noun" },
  { spanish: "segundo", english: "second", category: "noun" },
  { spanish: "jugar", english: "to play", category: "verb" },
  { spanish: "dormir", english: "to sleep", category: "verb" },
  { spanish: "abrir", english: "to open", category: "verb" },
  { spanish: "cerrar", english: "to close", category: "verb" },
  { spanish: "pagar", english: "to pay", category: "verb" },
  { spanish: "ayudar", english: "to help", category: "verb" },
  { spanish: "buscar", english: "to look for", category: "verb" },
  { spanish: "encontrar", english: "to find", category: "verb" },
  { spanish: "necesitar", english: "to need", category: "verb" },
  { spanish: "cambiar", english: "to change", category: "verb" },
  { spanish: "teléfono", english: "telephone", category: "noun" },
  { spanish: "computadora", english: "computer", category: "noun" },
  { spanish: "mesa", english: "table", category: "noun" },
  { spanish: "silla", english: "chair", category: "noun" },
  { spanish: "puerta", english: "door", category: "noun" },
  { spanish: "ventana", english: "window", category: "noun" },
  { spanish: "cama", english: "bed", category: "noun" },
  { spanish: "baño", english: "bathroom", category: "noun" },
  { spanish: "cocina", english: "kitchen", category: "noun" },
  { spanish: "escuela", english: "school", category: "noun" },
  { spanish: "útil", english: "useful", category: "adjective" },
  { spanish: "feliz", english: "happy", category: "adjective" },
  { spanish: "triste", english: "sad", category: "adjective" },
  { spanish: "cansado", english: "tired", category: "adjective" },
  { spanish: "ocupado", english: "busy", category: "adjective" },
  { spanish: "limpio", english: "clean", category: "adjective" },
  { spanish: "sucio", english: "dirty", category: "adjective" },
  { spanish: "fuerte", english: "strong", category: "adjective" },
  { spanish: "débil", english: "weak", category: "adjective" },
  { spanish: "enfermo", english: "sick", category: "adjective" },
  { spanish: "aquí", english: "here", category: "adverb" },
  { spanish: "allá", english: "there", category: "adverb" },
  { spanish: "despacio", english: "slowly", category: "adverb" },
  { spanish: "rápido", english: "quickly", category: "adverb" },
  { spanish: "temprano", english: "early", category: "adverb" },
  { spanish: "lluvia", english: "rain", category: "noun" },
  { spanish: "sol", english: "sun", category: "noun" },
  { spanish: "nube", english: "cloud", category: "noun" },
  { spanish: "viento", english: "wind", category: "noun" },
  { spanish: "tormenta", english: "storm", category: "noun" },
  { spanish: "nieve", english: "snow", category: "noun" },
  { spanish: "calor", english: "heat", category: "noun" },
  { spanish: "frío", english: "cold", category: "noun" },
  { spanish: "húmedo", english: "humid", category: "adjective" },
  { spanish: "soleado", english: "sunny", category: "adjective" },
  { spanish: "nublado", english: "cloudy", category: "adjective" },
  { spanish: "lluvioso", english: "rainy", category: "adjective" },
  { spanish: "camisa", english: "shirt", category: "noun" },
  { spanish: "pantalón", english: "pants", category: "noun" },
  { spanish: "zapatos", english: "shoes", category: "noun" },
  { spanish: "calcetines", english: "socks", category: "noun" },
  { spanish: "vestido", english: "dress", category: "noun" },
  { spanish: "falda", english: "skirt", category: "noun" },
  { spanish: "chaqueta", english: "jacket", category: "noun" },
  { spanish: "abrigo", english: "coat", category: "noun" },
  { spanish: "sombrero", english: "hat", category: "noun" },
  { spanish: "guantes", english: "gloves", category: "noun" },
  { spanish: "bufanda", english: "scarf", category: "noun" },
  { spanish: "gafas", english: "glasses", category: "noun" },
  { spanish: "nadar", english: "to swim", category: "verb" },
  { spanish: "cantar", english: "to sing", category: "verb" },
  { spanish: "pintar", english: "to paint", category: "verb" },
  { spanish: "dibujar", english: "to draw", category: "verb" },
  { spanish: "cocinar", english: "to cook", category: "verb" },
  { spanish: "limpiar", english: "to clean", category: "verb" },
  { spanish: "estudiar", english: "to study", category: "verb" },
  { spanish: "viajar", english: "to travel", category: "verb" },
  { spanish: "ejercicio", english: "exercise", category: "noun" },
  { spanish: "pasear", english: "to walk/stroll", category: "verb" },
  { spanish: "espejo", english: "mirror", category: "noun" },
  { spanish: "lámpara", english: "lamp", category: "noun" },
  { spanish: "alfombra", english: "rug", category: "noun" },
  { spanish: "cortina", english: "curtain", category: "noun" },
  { spanish: "almohada", english: "pillow", category: "noun" },
  { spanish: "sábana", english: "sheet", category: "noun" },
  { spanish: "manta", english: "blanket", category: "noun" },
  { spanish: "cuadro", english: "painting/picture", category: "noun" },
  { spanish: "plato", english: "plate", category: "noun" },
  { spanish: "vaso", english: "glass", category: "noun" },
  { spanish: "cuchara", english: "spoon", category: "noun" },
  { spanish: "tenedor", english: "fork", category: "noun" },
  { spanish: "cuchillo", english: "knife", category: "noun" },
  { spanish: "olla", english: "pot", category: "noun" },
  { spanish: "sartén", english: "pan", category: "noun" },
  { spanish: "norte", english: "north", category: "noun" },
  { spanish: "sur", english: "south", category: "noun" },
  { spanish: "este", english: "east", category: "noun" },
  { spanish: "oeste", english: "west", category: "noun" },
  { spanish: "derecha", english: "right", category: "noun" },
  { spanish: "izquierda", english: "left", category: "noun" },
  { spanish: "arriba", english: "up", category: "adverb" },
  { spanish: "abajo", english: "down", category: "adverb" },
  { spanish: "dentro", english: "inside", category: "adverb" },
  { spanish: "fuera", english: "outside", category: "adverb" },
  { spanish: "enfrente", english: "in front", category: "adverb" },
  { spanish: "detrás", english: "behind", category: "adverb" },
  { spanish: "al lado", english: "next to", category: "adverb" },
  { spanish: "cerca de", english: "near to", category: "preposition" },
  { spanish: "lejos de", english: "far from", category: "preposition" },
];
